//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoGridCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int tblEmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> tblDesignationID { get; set; }
        public Nullable<int> tblCityID { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual tblDesignation tblDesignation { get; set; }
    }
}
